[tools]
go = "latest"
hugo = "latest"
node = "latest"
npm = "latest"

[env]
_.path = ["./node_modules/.bin"]

[tasks.install]
description = "Install dependencies"
run = "npm install"

[tasks.build]
description = "Build example site"
run = "hugo --source exampleSite --minify --gc"
depends = ["install"]

[tasks.server]
description = "Run example site server in watch mode"
run = "hugo server --source exampleSite --buildDrafts --watch"
depends = ["install"]

[tasks.update]
description = "Update node dependencies"
run = "npm update"
