name = "Nerdy"
license = "MIT"
licenselink = "https://github.com/hugo-themes/nerdy/blob/main/LICENSE"
description = "A nerd vibed personal portfolio theme."
homepage = "https://github.com/hugo-themes/nerdy"
tags = [
  "blog",
  "personal",
  "portfolio",
  "tailwindcss",
  "alpinejs",
  "responsive",
  "dark-mode",
]
features = [
  "blog",
  "portfolio",
  "tailwindcss",
  "alpinejs",
  "dark-mode",
  "responsive",
]
min_version = "0.162.1"

[author]
name = "Hugo Themes"
homepage = "https://github.com/hugo-themes"
